### ISSUE TITLE
[suggestion] Adding pre-commit to improve code readability

### ISSUE THREAD

**Issue by conradogarciaberrotaran** [serengil/deepface#98]
Hi again, i have a suggestion to make the code more readable and thus make it easier to contribute: adding pre-commit to ensure the code is pythonic.
Link: https://pre-commit.com/
My current pre-commit configuration as reference:
.pre-commit-config.yaml
```
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v1.2.3
    hooks:
    - id: flake8
-   repo: https://github.com/asottile/seed-isort-config
    rev: v1.7.0
    hooks:
    -   id: seed-isort-config
-   repo: https://github.com/pre-commit/mirrors-isort
    rev: v4.3.4
    hooks:
    - id: isort
-   repo: https://github.com/ambv/black
    rev: stable
    hooks:
    - id: black
      language_version: python3
- repo: https://github.com/humitos/mirrors-autoflake.git
  rev: v1.1
  hooks:
    - id: autoflake
      args: ['--in-place', '--remove-all-unused-imports', '--remove-unused-variables']
```

This applies:
Flake8: https://flake8.pycqa.org/en/latest/
Isort: https://readthedocs.org/projects/isort/
Black: https://github.com/psf/black
Autoflake: https://github.com/myint/autoflake
